# Generated by Django 3.2.17 on 2023-02-07 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0054_scheduledjob_kwargs_request_user_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNACInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("host_url", models.CharField(blank=True, max_length=255)),
                ("port", models.IntegerField(default=443)),
                (
                    "auth_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="extras.secretsgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNA Center Instance",
                "verbose_name_plural": "DNA Center Instances",
                "ordering": ["name"],
            },
        ),
    ]
